### PR TITLE
new command join

### PR DESCRIPTION
**Pull request by KevinGossentCap**
Adding a new command "join" to additionally merge the files.
It's useful on some git flows and when we implement custom full retrieve split in multiple packages.
It will also start a look of better/easier merge in the futur (I'll start looking into it now that I experimented on join)

### CODE REVIEW

**Comment by KevinGossentCap** [comment]
@jayree for your review

**Comment by KevinGossentCap** [comment]
Too much changes to push back on master from my side.
@jayree  We'll have to discuss how/if we put back my improvements in the futur (look at my publish and v0.2.x branches)

**Comment by jayree** [comment]
@KevinGossentCap Definitely. I'll check it out in the next few days. I just need to finish my current project. It looks very promising. Maybe you will have time in the next few days to describe the underlying use case. Have you thought about making the command available as sfdx command?

**Comment by KevinGossentCap** [comment]
I'll do it definitely :)
Regarding making it as sfdx command : I tested it and came back out of it because of a simple "problem" => each call took an additional 2-3 seconds...
I'll push a deadend branch "feature/join_command" with my test of it (with really early join command added but can help you look into it). My interpretation of this additional time is that it is an impact of SFDX itself being bigger that only the OCLIF framework.

**Comment by KevinGossentCap** [comment]
@jayree 
Quick explanations on my changes
- adding join for melding files out of git process : on project we developed a job doing full retrieve of PROD metadata so we splitted as much as possible to not reach 10k components limit, we then need to merge some of the files (profiles, permissionset, translations, customObjTranslation, etc.)
- adding sort to help devs when they manually add parts or gitmerge to see things well (not easy to maintain an order equivalent to pur salesforce retrieve)
- from xml2js to xml-js : not deleting comments, especially for translations (i'm still looking at ways to parse faster or more in parallel if possible)
- I'm right now reworking the join to more heavily use lodash because it makes things easier to read
- rework on config to share some common useful definitions and not do a jsonparse (so faster)

**Comment by KevinGossentCap** [comment]
I also forgot the idea to ultimately be able to continue adding some metadataTypes like the most complex "customObject", which explains the partly recursive definition in new config

**Pull request closed without merging**
